/* ==========================================================================
   Santorini · 17–22 Aug — candidate places
   --------------------------------------------------------------------------
   This is the ONLY file to edit when adding a place. index.html reads it.

   One entry per place:
     name   required   what you'll recognise it by
     cat    required   one of the keys in CATS below (wine, dinner, snack,
                       brekky, beach, bar, site, hike, sail, stay). This order is also the
                       order sections appear in the app — rearrange it to reorder them.
     lat/lon required   decimal degrees. Right-click a spot in Google Maps and
                       the first menu item is "lat, lon" — paste it here.
     area   optional   village or coast, shown under the name
     note   optional   one line, why it's on the list
     status optional   'seed' (unverified idea, default) | 'maybe' | 'pick'
     url    optional   its own website — shown as "Website" in the app
     q      optional   override the Google Maps search text
     price  optional   what it costs, free text: '€8-20 tastings'
     dur    optional   duration / opening hours / booking note
     type   optional   what kind of place: 'taverna', 'falafel counter', 'ouzeri'
     also   optional   extra categories it also belongs to, e.g. also: ['bar']
     group  optional   sub-heading inside its category, e.g. 'Beach clubs'
     rank   optional   1 = top of its category; the app sorts by it
     verdict optional  one line on why it sits where it does in the order

   Adding a place = one line. Nothing else needs touching.
   ========================================================================== */

const CATS = {
  wine:   { label: 'Wine tasting',    color: '#7D4B6E', shape: 'hexagon'  },
  dinner: { label: 'Dinners',         color: '#B4653C', shape: 'circle'   },
  brekky: { label: 'Breakfast & brunch', color: '#B07C2E', shape: 'tri-down' },
  snack:  { label: 'Snacks & coffee', color: '#8C7A3F', shape: 'pill'     },
  beach:  { label: 'Beaches',         color: '#2E8B92', shape: 'pentagon' },
  bar:    { label: 'Bars & clubs',    color: '#A24B58', shape: 'octagon'  },
  site:   { label: 'Sights & indoor',  color: '#6C6497', shape: 'square'   },
  hike:   { label: 'Hiking & walks',  color: '#4E7C3F', shape: 'diamond'  },
  sail:   { label: 'Sailing',         color: '#3D6B87', shape: 'triangle' },
  stay:   { label: 'Where to stay',   color: '#54606B', shape: 'star'     },
};

const PLACES = [
  // ---- wine · grouped by distance from Megalochori, then ranked ----
  { name: 'Gavalas Winery', cat: 'wine', img: 'img/gavalas-winery.png', imgKind: 'venue', imgFrom: 'gavalaswines.gr', type: 'family winery', group: 'Walk from the base',
    lat: 36.3759, lon: 25.4312, area: 'Megalochori', rank: 3,
    price: 'Introduction €26 · White Expressions €35 · Explore €42 · Premium & Rare €52',
    dur: 'four tastings, 50–75 min, 18+, book online via FareHarbor',
    url: 'https://www.gavalaswines.gr/',
    note: 'Five generations and roughly three centuries of winemaking, 11 wines and about 90,000 bottles a year. The only winery on the island vinifying the rare Katsano and Voudomato grapes.',
    verdict: 'In your own village — the one tasting you can walk to and from, so nobody has to stay sober. Not cheap: €26 entry level, and Premium & Rare at €52 is where the Katsano and Voudomato live.' },
  { name: 'Artemis Karamolegos', cat: 'wine', img: 'img/artemis-karamolegos.webp', imgKind: 'venue', imgFrom: 'artemiskaramolegos-winery.com', group: 'Short drive — 15 min or less', lat: 36.3883, lon: 25.4636, area: 'Exo Gonia', rank: 8,
    price: '€8–20 tastings · €65–140 with food', dur: 'hourly tours 12:00–18:00, open 11–20 daily',
    url: 'https://www.artemiskaramolegos-winery.com/en/tasting-room/wine-tasting/',
    note: 'Tiered flights: 3 wines €8, 4 for €11, 5 for €14, 5 PDO for €15, 7 for €20. Sea-view courtyard, own restaurant.',
    verdict: 'Best value and the most flexible — drop-ins welcome, hourly tours, cheapest way to taste properly.' },
  { name: 'Canava Roussos', cat: 'wine', img: 'img/canava-roussos.jpg', imgKind: 'venue', imgFrom: 'santorinidave.com', type: 'oldest winery on the island', group: 'Short drive — 15 min or less',
    lat: 36.3841, lon: 25.4633, area: 'Mesa Gonia, on the Kamari road', rank: 1,
    price: '€3 a sample · €6 a glass',
    dur: 'guided tour of the old and new canava; open May–October',
    url: 'https://santorinidave.com/canava-roussos-winery-santorini',
    note: 'Founded 1836, five generations, the oldest winery on Santorini. Two canavas — the old one preserved as it was, the new one working. Seven wines including Nama and a Vinsanto from sun-dried Assyrtiko, Aidani and Athiri.',
    verdict: 'Cheapest way to taste properly anywhere on this list, and the only place where the room itself is nearly two centuries old.' },
  { name: 'Vassaltis Vineyards', cat: 'wine', img: 'img/vassaltis-vineyards.jpg', imgKind: 'venue', imgFrom: 'vassaltis.com', group: 'Short drive — 15 min or less', lat: 36.4344, lon: 25.4386, area: 'Vourvoulos', rank: 5,
    price: '€40 tasting · €30 cellar tour', dur: 'cellar tour 16:00–17:00, max 12 people',
    url: 'https://vassaltis.com/best-wine-experience-in-santorini/',
    note: '€40 = 4 wines with 4 designed bites. €30 = 1h cellar tour then 4 wines. Modern, small, close to Fira.',
    verdict: 'The best actual tasting — small groups, food thought through, no bus crowds.' },
  { name: 'Domaine Sigalas', cat: 'wine', img: 'img/domaine-sigalas.jpg', imgKind: 'venue', imgFrom: 'sigalas-wine.com', group: 'The north end — 25–30 min each way', lat: 36.4713, lon: 25.3943, area: 'Baxedes, near Oia', rank: 4,
    price: 'from €12 · pairing menus €100–150', dur: 'tasting room 11:00–21:00. By bus: Fira–Oia line, off at the Perivolos Hotel stop, then ~25 min walk',
    url: 'https://sigalas-wine.com/food-pairing-en/',
    note: 'Top-100 world winery listings, relaxed vineyard setting. Entry tastings are cheap; the 6-plate degustation is the splurge.',
    verdict: 'Most acclaimed wine, calm setting, and reachable without the car — bus to the Perivolos Hotel stop then walk 25 min. Pairs with an Oia or Ammoudi evening.' },
  { name: 'Estate Argyros', cat: 'wine', img: 'img/estate-argyros.webp', imgKind: 'venue', imgFrom: 'estateargyros.com', group: 'Short drive — 15 min or less', lat: 36.3836, lon: 25.4647, area: 'Episkopi Gonia', rank: 2,
    price: '€15 (60 min) · €40 (90 min)', dur: '4 wines + cheese, or 7 wines + platters',
    url: 'https://estateargyros.com/',
    note: 'Family estate since 1903, oldest vines on the island. Inland, no caldera view.',
    verdict: 'Most serious old-vine tasting per euro; skip if you want a view with it.' },
  { name: 'Hatzidakis Winery', cat: 'wine', img: 'img/hatzidakis-winery.jpg', imgKind: 'venue', imgFrom: 'hatzidakiswines.gr', group: 'Short drive — 15 min or less', lat: 36.3713, lon: 25.4394, area: 'Pyrgos Kallistis', rank: 7,
    price: '€20 for 6 wines · premium tiers €40–160', dur: '45–60 min, appointment only',
    url: 'https://www.hatzidakiswines.gr/en/visit-us',
    note: 'Organic, carved into a cave under its own vineyard. First to revive Mavrotragano.',
    verdict: 'Great story and cellar, but reviews split — some report short tours and small pours.', status: 'maybe' },
  { name: 'Venetsanos', cat: 'wine', img: 'img/venetsanos.jpg', imgKind: 'venue', imgFrom: 'venetsanoswinery.com', group: 'Short drive — 15 min or less', lat: 36.3825, lon: 25.4315, area: 'Megalochori, above Athinios', rank: 6,
    price: '€2 tour + €10 tasting', dur: 'short visit',
    url: 'https://venetsanoswinery.com/',
    note: 'The 1947 gravity-fed industrial winery built into the cliff above the ferry port.',
    verdict: 'Cheapest stop and the most dramatic building — a view with wine, not a deep tasting.' },
  { name: 'Pelican Kipos', cat: 'wine', img: 'img/pelican-kipos.png', imgKind: 'venue', imgFrom: 'pelicankipos.com', group: 'Short drive — 15 min or less', lat: 36.4184, lon: 25.4328, area: 'Fira centre', rank: 9,
    price: '€30', dur: '1 hour, 5 wines',
    url: 'https://www.pelicankipos.com/',
    note: 'Not a winery — a garden wine restaurant over a 400-year-old cave cellar, 600 labels. 3 whites, a red, a Vinsanto, with cheese and bread.',
    verdict: 'The in-town option: no driving, works as an evening or a hot-afternoon escape.' },
  { name: 'Santo Wines', cat: 'wine', img: 'img/santo-wines.jpg', imgKind: 'venue', imgFrom: 'santowines.gr', group: 'Short drive — 15 min or less', lat: 36.3876, lon: 25.4365, area: 'Pyrgos', rank: 10,
    price: 'flights €18–55', dur: 'book ahead for sunset',
    url: 'https://santowines.gr/',
    note: 'The big caldera-facing terrace. Reviews repeatedly call it commercial and crowded.',
    verdict: 'Last for the wine, first if the goal is sunset — book a front table or do not bother.' },

  // ---- dinners · sit-down meals, ranked ----
  { name: 'Raki', cat: 'dinner', img: 'img/raki.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'taverna', group: 'Walk from the base',
    lat: 36.3807, lon: 25.4258, area: 'Megalochori, by the three bell towers', rank: 1,
    note: 'Taverna in your own village, by the landmark three bell towers.',
    verdict: 'The dinner you can walk to. Nothing else on this list is closer.' },
  { name: 'Metaxi Mas', cat: 'dinner', img: 'img/metaxi-mas.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · C messier', type: 'taverna', group: 'Close to the base — 15 min or less', lat: 36.3880, lon: 25.4579, area: 'Exo Gonia', rank: 2,
    note: 'The island favourite. Inland, no caldera view, and it books out well ahead.',
    verdict: 'Best-loved proper dinner on the island — reserve now or lose it.' },
  { name: 'Pentozali', cat: 'dinner', img: 'img/pentozali.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · C messier', type: 'mezedopoleio', group: 'Close to the base — 15 min or less', lat: 36.3999, lon: 25.4478, area: 'Mesaria', rank: 5,
    price: '€15–20 per person', dur: 'no reservation needed, short wait possible',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g968383-d28123856-Reviews-Pentozali-Mesaria_Santorini_Cyclades_South_Aegean.html',
    note: 'Run by two Cretans: hot and cold mezedes, raki, house wine. Shaded patio, more Greeks than tourists. 4.8 over 745 reviews.',
    verdict: 'Best value real meal, and the only good one you can walk into.' },
  { name: 'Fratzeskos Fish Tavern', cat: 'dinner', img: 'img/fratzeskos-fish-tavern.jpg', imgKind: 'satellite', imgFrom: 'satellite view', type: 'fish taverna', group: 'Close to the base — 15 min or less', lat: 36.3530, lon: 25.4712, area: 'Perissa beachfront', rank: 7,
    price: 'grilled fish platter for two €45',
    url: 'https://www.e-table.gr/en/restaurant/fratzeskos',
    note: 'Family-run since 2006, catch landed daily and you pick your fish. Right on the sand, away from the hyped villages.',
    verdict: 'The fish dinner that is about the fish — pairs with a Perissa beach day.' },
  { name: 'Lava Tavern', cat: 'dinner', img: 'img/lava-tavern.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · ArticCynda', type: 'beach taverna', group: 'Close to the base — 15 min or less', lat: 36.3400, lon: 25.4560, area: 'Perivolos, Agios Georgios end', rank: 8,
    url: 'https://www.tripadvisor.com/Restaurant_Review-g635608-d1167801-Reviews-Lava-Perissa_Santorini_Cyclades_South_Aegean.html',
    note: 'No fixed menu — staff show you the day\'s dishes, bought that morning from fishermen and farmers. 4.4–4.5 across thousands of reviews.',
    verdict: 'Quiet end of the beach, whatever was fresh that morning. Unfussy and consistently loved.' },
  { name: 'Ouzeri', cat: 'dinner', img: 'img/ouzeri.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'ouzeri', group: 'Close to the base — 15 min or less', lat: 36.4158, lon: 25.4315, area: 'Fira, Fabrika centre', rank: 9,
    dur: 'lunch walk-in, book for dinner',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g482942-d1103026-Reviews-Ouzeri-Fira_Santorini_Cyclades_South_Aegean.html',
    note: 'Open since 2003, chef trained at Cordon Bleu. Sharing plates, grilled meat and seafood, moderate prices for Fira.',
    verdict: 'The in-town dinner: no driving, shared plates, reliably good value.' },
  { name: 'To Psaraki', cat: 'dinner', img: 'img/to-psaraki.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · ArticCynda', type: 'fish taverna', group: 'Close to the base — 15 min or less', lat: 36.3380, lon: 25.4350, area: 'Vlychada', rank: 6,
    url: 'https://topsaraki.gr/',
    note: 'Above the marina on the south coast.',
    verdict: 'Well regarded, but I have not verified prices or hours yet.' },
  { name: "Penelope's Ouzeri", cat: 'dinner', img: 'img/penelope-s-ouzeri.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Bernard Gagnon', type: 'mezedopoleio', group: 'Close to the base — 15 min or less',
    lat: 36.3826, lon: 25.4502, area: 'Pyrgos', rank: 3,
    url: 'https://www.tripadvisor.com/Restaurant_Review-g1097549-d2327988-Reviews-Penelope_s_Ouzeri_Pyrgos_Santorini-Pyrgos_Santorini_Cyclades_South_Aegean.html',
    note: 'Family-run in the centre of Pyrgos, looking over the village. Traditional mezedes with a modern turn — fava, tomatokeftedes, and the octopus reviewers keep naming.',
    verdict: 'Six minutes from your door and the sunset comes free with the view. Different place from Ouzeri in Fira.' },
  { name: 'I Spilia tou Nikola', cat: 'dinner', img: 'img/i-spilia-tou-nikola.webp', imgKind: 'venue', imgFrom: 'nikolascave.gr', type: 'cave fish taverna', group: 'Close to the base — 15 min or less',
    lat: 36.3486, lon: 25.3936, area: 'Akrotiri', rank: 4,
    url: 'https://nikolascave.gr/',
    note: 'The Cave of Nikolas: a boat shelter dug into the rock that turned taverna in 1967. Vegetables, cheese and meat from their own farm, fish landed that day. Famous for tomatokeftedes, meatless moussaka with white aubergine, grilled calamari. Gourmet award for best traditional taverna 2007–08.',
    verdict: 'Ten minutes away, on the water, and the produce is genuinely theirs — the best-value serious dinner near the base.' },
  { name: 'Krinaki', cat: 'dinner', img: 'img/krinaki.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · bynyalcin', type: 'farm-to-table taverna', group: 'The north end — 25–30 min each way',
    lat: 36.4632, lon: 25.3939, area: 'Finikia, next to Oia', rank: 11,
    price: '€30–40 per person with wine',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g10521928-d1812490-Reviews-Krinaki-Finikia_Santorini_Cyclades_South_Aegean.html',
    note: 'Raised terrace over the lanes of Finikia. The owner sources from village growers, so specials appear when someone turns up with good produce. 4.9 across 1,800 reviews.',
    verdict: 'The north-end dinner that is not a tourist tax — do this instead of eating in Oia itself.' },
  { name: 'Fino', cat: 'dinner', img: 'img/fino.jpg', imgKind: 'venue', imgFrom: 'finosantorini.gr', type: 'creative Greek', group: 'The north end — 25–30 min each way',
    lat: 36.4605, lon: 25.3752, area: 'Oia', rank: 12,
    dur: 'daily 14:00–22:00; closes at 22:00',
    url: 'https://finosantorini.gr/',
    note: 'Creative Greek cooking built around a strong local wine list, in a minimal room rather than on a cliff edge. They also run cooking classes.',
    verdict: 'The Oia dinner for the food rather than the view — and the 22:00 close means it is an early evening.' },
  { name: 'Anogi', cat: 'dinner', img: 'img/anogi.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Κλέαρχος Π. Καπούτσης', type: 'taverna', group: 'The north end — 25–30 min each way',
    lat: 36.4322, lon: 25.4234, area: 'Imerovigli', rank: 14,
    price: 'starters €6–22 · mains €22–26 · desserts €10–13',
    dur: 'site lists Fri–Sun 17:00–24:00 only — confirm August hours',
    url: 'https://anogisantorini.restaurant/menu/',
    note: 'Traditional Greek in Imerovigli: grilled octopus, kalamari, sea bass, lamb, Cretan pasta.',
    verdict: 'Watch the days — if Fri–Sun is right, Sunday 17 is your only shot, because Friday 22 is your flight.' },
  { name: 'Dimitris Ammoudi Taverna', cat: 'dinner', img: 'img/dimitris-ammoudi-taverna.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Anthony Baratier', type: 'fish taverna', group: 'The north end — 25–30 min each way', lat: 36.4650, lon: 25.3733, area: 'Ammoudi Bay, below Oia', rank: 13,
    price: '≈€70 per person with wine', dur: 'book a waterside table an hour before sunset',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g482941-d3221585-Reviews-Dimitris_Ammoudi_Taverna-Oia_Santorini_Cyclades_South_Aegean.html',
    note: 'Since 1989, tables at the waterline under the Oia cliff. 4.8 over 3,495 reviews, though several call it overpriced for what arrives.',
    verdict: 'The splurge you pay for the setting — worth one evening, not two.' },

  // ---- breakfast & brunch ----
  { name: 'Tholoto Brunch & Restaurant', cat: 'brekky', img: 'img/tholoto-brunch-restaurant.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', also: ['dinner'], type: 'brunch & restaurant', group: 'Close to the base — 15 min or less',
    lat: 36.4197, lon: 25.4356, area: 'Kontochori, Fira', rank: 10,
    dur: 'reservations recommended, especially for a table with a view',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g482942-d24000433-Reviews-Tholoto_Brunch_Restaurant-Fira_Santorini_Cyclades_South_Aegean.html',
    note: 'Greek and Mediterranean cooking from local produce, brunch through dinner. 4.9 over 6,571 reviews and a 2024 Travellers Choice award. Several reviews call it pricey for the area.',
    verdict: 'The polished option: brunch through dinner, so it covers a late start or an evening. Priciest of the three breakfasts.' },

  // ---- snacks, coffee & quick bites · grouped by distance from the base ----
  { name: 'Brusco Wine Coffee Deli', cat: 'snack', img: 'img/brusco-wine-coffee-deli.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Edal Anton Lefterov', also: ['brekky'], type: 'wine, coffee & deli', group: 'Close to the base — 15 min or less',
    lat: 36.3828, lon: 25.4497, area: 'Pyrgos square', rank: 1,
    price: 'platters €13–16',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g1097549-d6885554-Reviews-Brusco_Wine_Coffee_Deli-Pyrgos_Santorini_Cyclades_South_Aegean.html',
    note: 'Tables in the shaded village square. Coffee, pancakes and breakfast, local delicacies and small plates with Santorini wine by the glass. Vegetarian and vegan options. 4.6 across 466 reviews.',
    verdict: 'Six minutes away and cheaper than anything in Fira or Oia — the default morning stop, and it doubles as a wine snack in the evening.' },
  { name: 'Galini Cafe', cat: 'brekky', img: 'img/galini-cafe.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'brunch with a caldera view', group: 'Short drive — 15 min or less',
    lat: 36.4247, lon: 25.4285, area: 'Firostefani', rank: 2,
    dur: 'brunch from 08:00 — one of the few places open early',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g635607-d3492755-Reviews-Galini_Cafe-Firostefani_Santorini_Cyclades_South_Aegean.html',
    note: 'Open-air terrace looking at Skaros Rock and Imerovigli. 4.5 on TripAdvisor. Note it is in Firostefani, not Imerovigli as listed.',
    verdict: 'Opens at 08:00 and sits on the rim path — the natural breakfast at the end of the Oia hike, or the start of it.' },
  { name: 'Falafeland', cat: 'snack', img: 'img/falafeland.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'falafel counter', group: 'Close to the base — 15 min or less', lat: 36.4181, lon: 25.4336, area: 'Fira', rank: 2,
    price: '≈€3 a wrap', url: 'https://falafeland.gr/',
    note: 'Vegan street food in the middle of Fira. Wraps, homemade mayo, gluten-free options, vegan brownie.',
    verdict: 'Cheapest edible thing in Fira and genuinely good — the default hot-afternoon lunch.' },
  { name: 'Golden Grill House', cat: 'snack', img: 'img/golden-grill-house.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · C messier', type: 'charcoal grill', group: 'Close to the base — 15 min or less', lat: 36.4030, lon: 25.4450, area: 'Fira–Perissa road', rank: 3,
    price: 'gyros ≈€4.50',
    note: 'Charcoal grill, generous portions, sea view from the terrace, mostly locals. Seftalia is the thing to order.',
    verdict: 'Best cheap grill, but it is on the ring road — needs wheels or a bus.' },
  { name: "Brown's Espresso Bar", cat: 'snack', img: 'img/brown-s-espresso-bar.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Zde', type: 'espresso bar', group: 'The north end — 25–30 min each way', lat: 36.4330, lon: 25.4243, area: 'Imerovigli', rank: 4,
    url: 'https://mindtrip.ai/restaurant/imerovigli-south-aegean/browns-espresso-bar/re-Sl5MGtIS',
    note: 'Proper espresso, banana bread and cinnamon rolls. Sits right by the walking path — takeaway or sit down.',
    verdict: 'The coffee stop for the rim walk: it is on the Fira → Oia path, at the Imerovigli halfway point.' },

  { name: 'Lotza', cat: 'snack', img: 'img/lotza.jpg', imgKind: 'area', imgFrom: 'area photo · santorinidave.com', also: ['brekky'], type: 'cafe with a caldera view', group: 'The north end — 25–30 min each way',
    lat: 36.4614, lon: 25.3743, area: 'Oia, Nomikou walkway', rank: 5,
    price: 'breakfast good value · lunch and dinner €25–30pp · €7 for a small cappuccino',
    url: 'https://santorinidave.com/santorini-restaurant-lotza',
    note: 'Shaded patio over the caldera on the Oia walkway, open from breakfast onwards. Big portions, fast service. 4.1 across 4,077 reviews. Cliff-side tables go early.',
    verdict: 'The Oia breakfast with the view — and the cheapest way to sit on that cliff, as long as you ignore the coffee price.' },

  // ---- sailing · by departure port, nearest the base first ----
  { name: 'Catamaran cruise', cat: 'sail', img: 'img/semi-private-catamaran-from-vlychada.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'catamaran, 5 hours', group: 'Short drive — 15 min or less',
    lat: 36.3400, lon: 25.4275, area: 'most depart Vlychada marina', rank: 1, status: 'maybe',
    price: 'semi-private €100–135pp · shared from ~€70 · private charter €550–820 half day',
    dur: '5 hours, day or sunset departure',
    url: 'https://www.santorini-yachts.com/cruise/santorini-premium-daytime-catamaran-cruise/',
    note: 'Red, White and Black beaches, Black Mountain coves, under the Akrotiri lighthouse, then the hot springs. BBQ, salad, fruit and drinks included. Operators departing Vlychada: Spiridakos Sailing Cruises (santorini-yachts.com, running since 1986, 11 catamarans) and Caldera Yachting. Sunset Oia Sailing (sailing-santorini.com) is the most praised but departs Ammoudi, 30 min north.',
    verdict: 'The splurge. Only book it if you decide the money is worth it — otherwise the €5–8 Akrotiri water taxi already gets you to Red and White beaches.' },
  { name: 'Volcano tour', cat: 'sail', img: 'img/volcano-hot-springs-boat.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'traditional boat, half day', group: 'Short drive — 15 min or less',
    lat: 36.4182, lon: 25.4281, area: 'boats from Fira Old Port, Athinios or Vlychada', rank: 2,
    price: '≈€32–36 plus €5 crater entry', dur: 'about 6 hours, 1.5 h on the crater',
    url: 'https://www.getyourguide.com/santorini-volcano-l9788/',
    note: 'Boat to Nea Kameni for the crater walk, then Palea Kameni for the sulphur hot springs — you swim 30–50 m from the boat to reach them.',
    verdict: 'By far the cheapest way onto the volcano. No shade on the crater, so not a midday plan.' },

  { name: 'Balla Grill House', cat: 'snack', img: 'img/balla-grill-house.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Bernard Gagnon', type: 'gyros counter', group: 'The north end — 25–30 min each way',
    lat: 36.4322, lon: 25.4258, area: 'Imerovigli, by the bus stop', rank: 6,
    url: 'https://www.tripadvisor.com/Restaurant_Review-g635864-d28010198-Reviews-Balla_Grill_House-Imerovigli_Santorini_Cyclades_South_Aegean.html',
    note: 'Gyros, souvlaki and wraps at the Imerovigli bus stop. 4.9 from 776 Google ratings and far cheaper than anything else up there.',
    verdict: 'Lunch at the exact point you bail out of the Oia hike — the bus stop is right there.' },

  { name: 'Taxi boats to Red, White & Black', cat: 'sail', img: 'img/taxi-boats-to-red-white-black.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Klearchos Kapoutsis from Santorini, Gr', type: 'hop-on boat', group: 'Short drive — 15 min or less',
    lat: 36.3520, lon: 25.3960, area: 'Akrotiri harbour', rank: 3,
    price: '€5–15 per person', dur: 'boats roughly every 30 min, hop on and off',
    url: 'https://www.tripadvisor.com/Attraction_Review-g1189834-d11777498-Reviews-Taxi_Boats_to_Red_White_and_Black_Beach-Akrotiri_Santorini_Cyclades_South_Aegea.html',
    note: 'Small boats shuttling Red Beach, White Beach and Black Beach from Akrotiri harbour. Get off where you like and pick up a later boat.',
    verdict: 'This is the cheap version of the three-beach cruise — and the safe way to see Red Beach with the cliff path closed.' },

  // ---- beaches · natural beaches only; beach clubs live under Bars & clubs ----
  { name: 'Perissa / Perivolos', cat: 'beach', img: 'img/perissa-perivolos.jpg', imgKind: 'satellite', imgFrom: 'satellite view', type: 'beach',
    lat: 36.3523, lon: 25.4723, area: 'south-east', rank: 1,
    note: 'Kilometres of black sand, the most organised stretch on the island.',
    verdict: 'Easiest full beach day, and where most of the beach clubs are.' },
  { name: 'Vlychada beach', cat: 'beach', img: 'img/vlychada-beach.jpg', imgKind: 'photo', imgFrom: 'Wikimedia · Dietmar Rabich', type: 'beach',
    lat: 36.3400, lon: 25.4310, area: 'south', rank: 2,
    note: 'Wind-carved pale cliffs standing behind the sand, quieter than Perivolos.',
    verdict: 'The one worth seeing for the landscape rather than the sunbeds.' },
  { name: 'Kamari', cat: 'beach', img: 'img/kamari.jpg', imgKind: 'photo', imgFrom: 'Wikimedia · Jules Verne Times Two', type: 'beach',
    lat: 36.3769, lon: 25.4744, area: 'east', rank: 3,
    note: 'Under Mesa Vouno — dark pebbles, long promenade, sunbeds.',
    verdict: 'Good if you want shops and food right behind the beach.' },
  { name: 'White Beach', cat: 'beach', img: 'img/white-beach.jpg', imgKind: 'venue', imgFrom: 'daytripsfromsantorini.com', type: 'beach, boat access',
    lat: 36.3503, lon: 25.3823, area: 'Akrotiri, past Red Beach', rank: 4,
    price: '≈€15 boat round trip',
    url: 'https://daytripsfromsantorini.com/articles/white-beach-santorini',
    note: 'Aspri Paralia — a cove of grey pebbles under white limestone cliffs. Boat from Akrotiri harbour, 10–15 min, or a rough scramble from Red Beach. Wading ashore is likely.',
    verdict: 'A short excursion, not a beach day — bring your own food, facilities are minimal.' },

  { name: 'Forty One', cat: 'beach', img: 'img/forty-one.jpg', imgKind: 'venue', imgFrom: 'forty-one.site', type: 'beach club & sushi bar', group: 'Beach clubs',
    lat: 36.3399, lon: 25.4539, area: 'Perivolos beach', rank: 9,
    dur: 'sunbed and cabana packages, bookable; prices not published',
    url: 'https://forty-one.site/',
    note: 'Greek Mediterranean cooking with a sushi bar, on the black sand. Packages bundle sunbeds or a cabana (max 4) with prosecco or champagne, towels, fruit and a sushi combo. 4.77 across 1,691 reviews.',
    verdict: 'The food-led club — go for lunch rather than for the beds. Not the same as Forty One Caldera, their cliffside place in Fira.' },
  { name: 'Seaside Santorini', cat: 'beach', img: 'img/seaside-santorini.jpg', imgKind: 'satellite', imgFrom: 'satellite view', type: 'beach club', group: 'Beach clubs',
    lat: 36.3396, lon: 25.4522, area: 'Perivolos beach', rank: 10,
    price: 'sunbeds ≈€25 · packages with a minimum spend up to €200',
    dur: 'call ahead to book a bed or a table',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g657830-d1893185-Reviews-Seaside_Santorini-Perivolos_Santorini_Cyclades_South_Aegean.html',
    note: 'Beachfront restaurant, bar, cabanas and Balinese beds, plus a fashion shop. Also listed as SeaSide by Notos. 4.2 from 208 ratings.',
    verdict: 'The polished, pricier end of Perivolos. Watch the minimum spend — one report puts a bed with rosé or sushi at €200.' },

  // ---- bars & clubs · night venues, nearest the base first. Beach clubs live under Beaches ----
  { name: 'Red Beach (Kokkini Paralia)', cat: 'beach', img: 'img/red-beach-kokkini-paralia.jpg', imgKind: 'photo', imgFrom: 'Wikimedia · Dietmar Rabich', type: 'beach, boat access', lat: 36.3489, lon: 25.3931,
    area: 'Akrotiri', rank: 5,
    price: 'boat from Akrotiri harbour €5–8, ~10 min',
    dur: 'cliff path officially closed — ask at the car park or the Akrotiri site before walking',
    url: 'https://daytripsfromsantorini.com/articles/red-beach-santorini',
    note: 'Red volcanic cliffs over dark sand. Major rockfalls in 2018, 2023 and December 2025; people have been injured, and authorities tell hotels to discourage the cliff path. On the sand, stay near the waterline and away from the cliff base.',
    verdict: 'See it from the boat, not the path. Same cliffs, none of the falling rock — and the same boat carries on to White Beach.' },
  { name: 'Theros Wave Bar', cat: 'beach', img: 'img/theros-wave-bar.jpg', imgKind: 'satellite', imgFrom: 'satellite view', type: 'beach club', group: 'Beach clubs',
    lat: 36.3455, lon: 25.4230, area: 'Eros beach, Vlychada', rank: 7,
    price: 'sunbeds €30 back row · €60 second · €120 front',
    dur: 'daily 10:00–21:00; book 2–3 days ahead in peak season',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g1188919-d3584906-Reviews-Theros_Wave_Bar-Vlychada_Santorini_Cyclades_South_Aegean.html',
    note: 'Volcanic rock backdrop on the quiet end of Vlychada, voted among the best beach bars in the Mediterranean. Secluded compared with the Perivolos strip.',
    verdict: 'The closest club to the base, the calmest, and the only one publishing a clear price ladder. Some reviews report price inconsistencies — confirm the row before you sit.' },
  { name: 'Naboo Beach Bar', cat: 'beach', img: 'img/naboo-beach-bar.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · originaly owned and uploaded by Κλέαρχ', type: 'beach club', group: 'Beach clubs',
    lat: 36.3541, lon: 25.3763, area: 'Mesa Pigadia (Black Beach), Akrotiri', rank: 6,
    price: 'sunbeds free with any order · front row €25pp minimum',
    url: 'https://naboo.gr/en/our-place',
    note: 'Pebble beach on the Akrotiri side. Free loungers if you buy something, and they lend out snorkels and water shoes for the rocky entry.',
    verdict: 'The beach-club feeling without the beach-club bill — the cheapest of the four by a distance.' },
  { name: 'Wet Stories', cat: 'beach', img: 'img/wet-stories.jpg', imgKind: 'venue', imgFrom: 'wetstoriessantorini.gr', type: 'beach club', group: 'Beach clubs',
    lat: 36.3420, lon: 25.4590, area: 'Perivolos beach', rank: 8,
    price: 'sunbeds ≈€20–60 · front row €80+ · VIP €125+',
    dur: 'daily ≈10:00–22:00, later when busy; reserve ahead in August',
    url: 'https://wetstoriessantorini.gr/',
    note: 'Sunbeds and cabanas on the black sand, towels, showers, changing rooms, Mediterranean food, a boutique, and local and international DJs playing house and deep house that builds through the afternoon.',
    verdict: 'A day club, not a night club — the party peaks late afternoon and it winds down around 21:00–22:00. Prices quoted vary wildly by source; confirm what €20 actually buys before you sit down.' },
  { name: "Franco's Cafe", cat: 'bar', img: 'img/franco-s-cafe.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Klearchos Kapoutsis from Santorini, Gr', type: 'sunset cocktail terrace',
    lat: 36.3830, lon: 25.4508, area: 'top of Pyrgos', rank: 1,
    dur: 'no vehicle access to the top — park below and walk up the lanes',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g1097549-d1534236-Reviews-Franco_s_Cafe-Pyrgos_Santorini_Cyclades_South_Aegean.html',
    note: 'Terraces at the highest point of Pyrgos with a 360° view of the island. Classical and opera in the evening, easy jazz in the morning, strong cocktails. Reviewers call it the sunset without the Oia crowds.',
    verdict: 'Six minutes from the base and the best sunset seat on the island that is not a scrum. Not the Franco\'s Bar in Fira — this is the Pyrgos one.' },
  { name: 'PK Cocktail Bar', cat: 'bar', img: 'img/pk-cocktail-bar.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Beatriz Posada Alonso', type: 'cliffside cocktail bar',
    lat: 36.4176, lon: 25.4292, area: 'Fira, caldera edge', rank: 2,
    price: 'cocktails €12–16 · €20 deposit for a sunset table, taken off the bill',
    dur: 'book well ahead for a front-row sunset table',
    url: 'https://www.tripadvisor.com/Attraction_Review-g482942-d7140060-Reviews-PK_Cocktail_Bar-Fira_Santorini_Cyclades_South_Aegean.html',
    note: 'Multi-level terraces straight over the caldera. 1,656 reviews and repeatedly named the best cocktails in Fira.',
    verdict: 'The one to book if you want a proper cocktail with the view. Reserve or you are standing at the back.' },
  { name: 'Kira Thira Jazz Bar', cat: 'bar', img: 'img/kira-thira-jazz-bar.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'jazz bar in a cave house',
    lat: 36.4165, lon: 25.4310, area: 'Fira', rank: 3,
    dur: 'open all year, no view — this one is about the room',
    url: 'https://www.tripadvisor.com/Attraction_Review-g482942-d6628797-Reviews-Kira_Thira_Jazz_Bar-Fira_Santorini_Cyclades_South_Aegean.html',
    note: 'Opened 1976, the oldest bar on the island: a cave house hung with instruments, candlelight, classic and acid jazz, Latin and African records.',
    verdict: 'Where to go after dinner in Fira when you want music and a room, not a terrace.' },
  { name: 'Vitrin', cat: 'bar', img: 'img/vitrin.png', imgKind: 'venue', imgFrom: 'vitrinoia.gr', also: ['snack'], type: 'creperie by day, bar at night', group: 'The north end — 25–30 min each way',
    lat: 36.4609, lon: 25.3733, area: 'Oia, west side', rank: 5,
    url: 'https://vitrinoia.gr',
    note: 'High on the west side of Oia looking at Thirasia. Crepes, coffee and salads by day, cocktails and wine at night.',
    verdict: 'Called the best sunset seat in Oia if you get a table — cheaper than the cliff restaurants for the same view.' },
  { name: 'Hassapiko', cat: 'bar', img: 'img/hassapiko.webp', imgKind: 'venue', imgFrom: 'welltraveledclub.com', type: 'bar & dance floor',
    lat: 36.4612, lon: 25.3759, area: 'Oia', rank: 4,
    dur: 'open almost around the clock',
    url: 'https://www.welltraveledclub.com/santorini/hassapiko-bar',
    note: 'Also listed as Marykay\'s. Cocktails, DJs and actual dancing in a rustic room off the main street. 4.5 across 438 reviews.',
    verdict: 'Widely called the only real bar in Oia — the one place up there that is not a sunset terrace.' },

  // ---- hiking · Santorini's official numbered trails, grouped by distance ----
  { name: 'Trail 06 — Megalochori to Pyrgos', cat: 'hike', img: 'img/trail-06-megalochori-to-pyrgos.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · ArticCynda', type: 'official trail, 2.5 km', group: 'Walk from the base',
    lat: 36.3798, lon: 25.4379, area: 'from your village', rank: 1,
    price: 'free', dur: '2.5 km one way, roughly 45 min',
    note: 'Signposted island trail from Megalochori up to Pyrgos, through vineyards and old field walls.',
    verdict: 'Walk out of the door and arrive at Brusco, Penelope\'s and Franco\'s — the one hike that removes the car from an evening.' },
  { name: 'Trail 07 — Megalochori to Plaka', cat: 'hike', img: 'img/trail-07-megalochori-to-plaka.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Norbert Nagel', type: 'official trail, 1.3 km', group: 'Walk from the base',
    lat: 36.3766, lon: 25.4265, area: 'from your village', rank: 2,
    price: 'free', dur: '1.3 km, about 25 min',
    note: 'The short one, heading down the western side of the village.',
    verdict: 'A stretch of the legs before dinner rather than a hike.' },
  { name: 'Trail 03 — Perissa to Ancient Thera to Kamari', cat: 'hike', img: 'img/trail-03-perissa-to-ancient-thera-to-kamari.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Sidvics', type: 'official trail, 3 km + ruins', group: 'Short drive — 15 min or less',
    lat: 36.3671, lon: 25.4762, area: 'Mesa Vouno', rank: 3,
    price: 'site entry €10 (sources vary €4–10)',
    dur: 'Ancient Thera open daily except WEDNESDAY, 08:30–15:30. Kamari ascent 1.6 km, about 1 h; full Perissa–Thera–Kamari loop 4–4.5 h',
    url: 'https://santorinidave.com/santorini-ancient-thera',
    note: 'Zigzag cobbled climb up Mesa Vouno to the clifftop ruins, with both coasts below. Steep, no shade, and the site closes at 15:30.',
    verdict: 'Do the Kamari side up and down unless you want a four-hour day. Go early — and never on a Wednesday.' },
  { name: 'Trail 13 — Akrotiri to Vlychada beach', cat: 'hike', img: 'img/vlychada-cliffs-walk.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Dietmar Rabich', type: 'official trail, 1 km', group: 'Short drive — 15 min or less',
    lat: 36.3524, lon: 25.4162, area: 'south coast', rank: 4,
    price: 'free', dur: '1 km, flat, about 20 min',
    note: 'Short coastal walk under the white ash cliffs into Vlychada beach.',
    verdict: 'Pairs with a Vlychada beach day or Theros — not a hike in its own right.' },
  { name: 'Fira → Imerovigli → Oia rim path', cat: 'hike', img: 'img/fira-imerovigli-oia-rim-path.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Zde', type: 'the classic, 10.5 km', group: 'The north end — 25–30 min each way',
    lat: 36.4326, lon: 25.4228, area: 'caldera rim (Trail 09)', rank: 5,
    price: 'free', dur: '10.5 km, 2.5–5 h with stops. In August start 06:00–08:00',
    url: 'https://santorinidave.com/fira-oia-hike',
    note: 'Paved as far as Imerovigli, then 4 km of rocky, fully exposed ground to Oia. Moderate, with steep sections and no shade on the second half. Carry all your water.',
    verdict: 'The best walk on the island and the one most likely to break you in August — early morning or not at all. Brown\'s Espresso Bar sits at the Imerovigli halfway point.' },

  // ---- sites & indoor · ranked ----
  { name: 'Symposion by La Ponta', cat: 'site', img: 'img/symposion-by-la-ponta.jpg', imgKind: 'venue', imgFrom: 'symposionsantorini.com', type: 'arts, music & wine venue', group: 'Walk from the base', lat: 36.3770, lon: 25.4325,
    area: 'Megalochori', rank: 1,
    price: 'grounds free · tour €12 · workshop €20 · evening show €15',
    dur: 'Tue–Sun 10:00–19:00, closed Mondays. Tour 12:00, workshop 13:30. Odysseus Returns: Wednesdays. Booking required',
    url: 'https://www.symposionsantorini.com/your-visit',
    note: 'A restored late-1700s winery run by instrument maker Yannis Pantazis: vintage Greek instruments, an artisan workshop, photography, a mythological botanical garden, the Homeric wine café, and wine tasting of four Greek wines on request.',
    verdict: 'The one place here that is music, art and wine at once — and Wed 20 Aug is your only shot at the Odysseus Returns performance.' },
  { name: 'Heart of Santorini', cat: 'site', img: 'img/heart-of-santorini.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Klearchos Kapoutsis from Santorini, Gr', type: 'viewpoint', group: 'Walk from the base',
    lat: 36.3750, lon: 25.4240, area: 'Megalochori, caldera side', rank: 2,
    price: 'free, no gate or ticket',
    note: 'A heart-shaped hole worn through the caldera rock, framing the sea and the volcano, near the Agios Nikolaos chapel. About ten minutes on foot from the Boutari winery stop.',
    verdict: 'In your village and free. Go at sunset when the light comes through the gap. Coordinate is approximate — it is not mapped.' },
  { name: 'MATI Mesaria', cat: 'site', img: 'img/mati-mesaria.jpg', imgKind: 'venue', imgFrom: 'matiartgallery.com', type: 'gallery in a canava', group: 'Short drive — 15 min or less', lat: 36.4009, lon: 25.4455,
    area: 'Mesaria', rank: 3,
    dur: 'Tue–Sun 11:00–19:00, closed Mondays (1 May – 15 Oct)',
    url: 'https://matiartgallery.com/location/mati-mesaria/',
    note: 'Opened 2024 in a restored 1900s canava: a permanent Yorgos Kypris solo show, changing exhibitions, artist residencies, plus guided art tours with wine pairing from a local vineyard.',
    verdict: 'The art stop that doubles as a wine stop, in a quiet village — closest thing to Symposion in spirit. Tour prices are not published.' },
  { name: 'Akrotiri excavation', cat: 'site', img: 'img/akrotiri-excavation.jpg', imgKind: 'photo', imgFrom: 'Wikimedia · Norbert Nagel', type: 'archaeological site', group: 'Short drive — 15 min or less', lat: 36.3517, lon: 25.4033, area: 'Akrotiri', rank: 4,
    note: 'Bronze Age town under a roof — the good midday-heat option.',
    verdict: 'The island\'s essential site, and shaded.' },
  { name: 'MATI Fira', cat: 'site', img: 'img/mati-fira.jpg', imgKind: 'venue', imgFrom: 'matiartgallery.com', type: 'gallery', group: 'Short drive — 15 min or less', lat: 36.4159, lon: 25.4311,
    area: 'Fira, Fabrica centre', rank: 5,
    dur: 'August: Mon–Fri 10:00–23:00, Sat–Sun 10:00–20:00',
    url: 'https://matiartgallery.com/location/mati-fira/',
    note: 'Kypris\'s contemporary sculpture — the Frozen Fish, Shipwrecks and Cages & Flights series — plus etchings and jewellery. "Mati" means eye.',
    verdict: 'Open until 23:00 in August, in the same courtyard as Ouzeri. A walk-in after dinner, not a plan.' },


  { name: 'Skaros Rock', cat: 'hike', img: 'img/skaros-rock.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Zde', type: 'official spur, 1 km return', group: 'The north end — 25–30 min each way',
    lat: 36.4324, lon: 25.4182, area: 'Imerovigli (Trail SK)', rank: 6,
    price: 'free', dur: '1 km return, steep down and back up, 30–45 min',
    note: 'The ruined Venetian castle rock below Imerovigli, with the Theoskepasti chapel out on the headland.',
    verdict: 'Best viewpoint on the caldera and it is a spur off the Oia hike — do it even if you bail out at Imerovigli.' },  { name: 'Cape Akrotiri Lighthouse', cat: 'site', img: 'img/cape-akrotiri-lighthouse.jpg', imgKind: 'area', imgFrom: 'area photo · Wikimedia · Dietmar Rabich', type: 'sunset viewpoint', group: 'Short drive — 15 min or less',
    lat: 36.3577, lon: 25.3571, area: 'Faros, south-west tip', rank: 6,
    price: 'free',
    note: 'The 1892 lighthouse on the far south-west cape. Trail 12 walks here from Akrotiri, 8.2 km, or you drive.',
    verdict: 'Sunset with almost nobody there — the anti-Oia. Bring a torch for the walk back to the car.' },

  // ---- where to stay ----
  { name: 'Our Airbnb', cat: 'stay', img: 'img/base-megalochori.jpg', imgKind: 'satellite', imgFrom: 'satellite view', type: 'base',
    lat: 36.3764, lon: 25.4317, area: 'Megalochori', rank: 1, status: 'pick',
    note: 'Booked. Village-centre coordinates until you give me the exact address.',
    verdict: 'South-central base: Venetsanos and Symposion are in this village; Akrotiri, Vlychada and Pyrgos are ~10 minutes. Oia and Ammoudi are the long haul, ~25–30 minutes each way.' },
];

/* Fixed points — always on the map, never filtered. */
const ANCHORS = [
  { name: 'Thira airport (JTR)', lat: 36.3992, lon: 25.4793, note: 'Land 13:30 Sun 17 · fly 19:30 Fri 22' },
  { name: 'Athinios port', lat: 36.3843, lon: 25.4271, note: 'Ferries leave from here' },
  // { name: 'Hotel', lat: 0, lon: 0, note: 'Not booked yet' },
];

/* Routes drawn as lines rather than pins. */
const ROUTES = [
  { name: 'Fira → Imerovigli → Oia rim path', color: '#4E7C3F',
    points: [[36.4167, 25.4286], [36.4260, 25.4250], [36.4325, 25.4220], [36.4420, 25.4080],
             [36.4520, 25.3930], [36.4600, 25.3800], [36.4618, 25.3755]] },
];
